### PR TITLE
Workaround for Species enum containing both keys and values

### PR DESCRIPTION
**Pull request by abend**
Hi. This is a quick fix for #10. I can rework it or otherwise make changes if you like. This got me up and running again.

Thanks!

### CODE REVIEW

**Comment by mtskillman** [comment]
change line 236 of js/render.js to
`universe.paint(Species.Air, 0, 2, Species.Air);`

"Species" instead of "species"

**Comment by mtskillman** [comment]
i cherry-picked your commit and added the change mentioned above, as well:
https://github.com/MaxBittker/orb.farm/pull/12

**Comment by MaxBittker** [comment]
hey! thanks for the fix :-) 

I'm guessing this was a change from `wasm-bindgen`, not sure why they chose this new behavior.

**Comment by MaxBittker** [comment]
it was this change... https://github.com/rustwasm/wasm-bindgen/pull/2240

**Pull request merged**
